name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24-dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verificar Docker
        run: docker --version

      - name: Rodar Maven com Testcontainers
        env:
          POSTGRES_DB:       ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER:     ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT:     ${{ secrets.POSTGRES_PORT }}
          JWT_SECRET:        ${{ secrets.JWT_SECRET }}
        run: mvn clean verify
